module.exports = {
  whitelist: [
    'rtl',
    'home',
    'blog',
    'archive',
    'date',
    'error404',
    'logged-in',
    'admin-bar',
    'no-customize-support',
    'custom-background',
    'wp-custom-logo',
    'alignnone',
    'alignright',
    'alignleft',
    'wp-caption',
    'wp-caption-text',
    'screen-reader-text',
    'comment-list',
    'post-page-numbers',
    'current',
    'page-nav',
    'mce-content-body',
  ],
  whitelistPatterns: [
    /^search(-.*)?$/,
    /^(.*)-template(-.*)?$/,
    /^(.*)?-?single(-.*)?$/,
    /^postid-(.*)?$/,
    /^attachmentid-(.*)?$/,
    /^attachment(-.*)?$/,
    /^page(-.*)?$/,
    /^(post-type-)?archive(-.*)?$/,
    /^author(-.*)?$/,
    /^category(-.*)?$/,
    /^tag(-.*)?$/,
    /^tax-(.*)?$/,
    /^term-(.*)?$/,
    /^(.*)?-?paged(-.*)?$/,
    /^wp-core(-.*)?$/,
    /^edit-widgets(-.*)?$/,
    /^edit-post(-.*)?$/,
    /^(widefat|ui-dialog)?$/,
    /^type-(.*)$/,
    // gutenberg
    /^wp-block(-.*)?$/,
    /^editor-(.*)$/,
    /^block-library(-.*)?$/,
    /^block-editor(-.*)?$/,
    /^has-(.*)$/,
    /^is-(.*)$/,
    /^columns-([0-9]+)$/, // gallery block
    /^size-(.*)$/, // image block
    // acf
    /^(remove|order|filters|filter|selection|choices|list|values|-border)$/, // acf
    /^acf-(.*)$/,
    // facetwp
    /^fwp-(.*)$/,
    /^facetwp-(.*)$/,
    // Forms
    /(select|input|textarea|button)/,
  ],
  foundationSitesPatterns: [
    /^dropdown$/,
    /^opens-(left|right|up|down)$/,
  ],
  woocommercePatterns: [
    /^(variations|reset_variations|products)$/,
    /^(cart|quantity|qty|add_to_cart_button|button|alt)$/,
    /^woocommerce-/,
    /^product_type_(variable|single|group)/,
    /^(single|variable|group)_(add_to_cart_button|variation|variation_wrap)$/,
    /^(instock|purchasable|taxable)$/,
  ],
};
